---
###############################################################################
# Configuration of OpenStack user environment for SIB.

# Path to create virtualenv in which to install python dependencies.
#sib_venv:

# List of OpenStack projects. Format is as required by the stackhpc.os-projects
# role.
sib_projects:
  - "{{ sib_demo_project }}"

# Definition of the sib demo project. Format is as required by the
# stackhpc.os-projects role.
sib_demo_project:
  name: demo
  description: SIB demo project
  project_domain: default
  user_domain: default
  users: "{{ sib_demo_users }}"
  quotas: "{{ sib_demo_quotas }}"

# List of users in the sib demo project. Format is as required by the
# stackhpc.os-projects role.
sib_demo_users:
  - name: demo-user
    password: "abc123"
    roles: "{{ sib_admin_roles }}"

# List of roles to apply to admin users in the sib demo project.
sib_admin_roles:
  - admin
  - heat_stack_owner

# List of roles to apply to regular users in the sib demo project.
sib_user_roles:
  - heat_stack_owner
  - observer

# Dict of quotas to set for the sib demo project.
sib_demo_quotas:
  cores: -1
  floating_ips: -1
  injected_files: -1
  injected_file_size: -1
  instances: -1
  key_pairs: -1
  fixed_ips: -1
  ram: -1
  secgroup_rules: -1
  secgroups: -1

###############################################################################
# Configuration of networks, subnets and routers for SIB.

# List of networks in the sib system. Format is as required by the
# stackhpc.os-networks role.
sib_networks:
  - "{{ sib_network_internal }}"
  - "{{ sib_network_demo_vlan }}"
  - "{{ sib_network_demo_vxlan }}"
  - "{{ sib_network_public }}"

# Public network name.
sib_network_public_name: "public"

# Public network.
sib_network_public:
  name: "{{ sib_network_public_name }}"
  provider_network_type: "vlan"
  provider_physical_network: "physnet1"
  provider_segmentation_id: 79
  shared: True
  # Subnet configuration.
  subnets:
    - "{{ sib_subnet_public }}"

# Public subnet.
sib_subnet_public:
  name: "{{ sib_network_public_name }}"
  cidr: "10.12.9.0/24"
  gateway_ip: "10.12.9.1"
  allocation_pool_start: "10.12.9.10"
  allocation_pool_end: "10.12.9.127"
  # host_routes:
  #   - destination: "10.4.0.0/16"
  #     nexthop: "10.60.253.255"

# SIB internal network name.
sib_network_internal_name: "internal"

# SIB internal network.
sib_network_internal:
  name: "{{ sib_network_internal_name }}"
  project: "admin"
  provider_network_type: "vlan"
  provider_physical_network: "physnet1"
  provider_segmentation_id: 74
  shared: false
  # Subnet configuration.
  subnets:
    - "{{ sib_subnet_internal }}"

# SIB internal subnet.
sib_subnet_internal:
  name: "{{ sib_network_internal_name }}"
  project: "admin"
  cidr: "10.12.4.0/24"
  enable_dhcp: false
  allocation_pool_start: "10.12.4.2"
  allocation_pool_end: "10.12.4.4"

# SIB demo VLAN network name.
sib_network_demo_vlan_name: "demo-vlan"

# SIB demo VLAN network.
sib_network_demo_vlan:
  name: "{{ sib_network_demo_vlan_name }}"
  project: "{{ sib_demo_project.name }}"
  provider_network_type: "vlan"
  provider_physical_network: "physnet1"
  # Subnet configuration.
  subnets:
    - "{{ sib_subnet_demo_vlan }}"

# SIB demo VLAN subnet.
sib_subnet_demo_vlan:
  name: "{{ sib_network_demo_vlan_name }}"
  project: "{{ sib_demo_project.name }}"
  cidr: "10.0.0.0/24"
  gateway_ip: "10.0.0.1"
  allocation_pool_start: "10.0.0.2"
  allocation_pool_end: "10.0.0.254"

# SIB demo VXLAN network name.
sib_network_demo_vxlan_name: "demo-vxlan"

# SIB demo VXLAN network.
sib_network_demo_vxlan:
  name: "{{ sib_network_demo_vxlan_name }}"
  project: "{{ sib_demo_project.name }}"
  provider_network_type: "vxlan"
  # Subnet configuration.
  subnets:
    - "{{ sib_subnet_demo_vxlan }}"

# SIB demo VXLAN subnet.
sib_subnet_demo_vxlan:
  name: "{{ sib_network_demo_vxlan_name }}"
  project: "{{ sib_demo_project.name }}"
  cidr: "10.1.0.0/24"
  gateway_ip: "10.1.0.1"
  allocation_pool_start: "10.1.0.2"
  allocation_pool_end: "10.1.0.254"

# List of routers in the sib demo project. Format is as required by the
# stackhpc.os-networks role.
sib_routers:
  - "{{ sib_router_provision }}"
  - "{{ sib_router_demo }}"

# SIB bare metal provisioning router.
sib_router_provision:
  - name: "provision"
    project: "admin"
    interfaces:
      - net: "{{ sib_network_internal_name }}"
        subnet: "{{ sib_network_internal_name }}"
        portip: "10.12.4.2"
      - net: "provision-net"
        subnet: "provision-net"
        portip: "10.12.8.1"

# SIB demo router.
sib_router_demo:
  - name: "{{ sib_demo_project.name }}"
    project: "{{ sib_demo_project.name }}"
    interfaces:
      - "{{ sib_network_demo_vlan_name }}"
      - "{{ sib_network_demo_vxlan_name }}"
    network: "{{ sib_network_public_name }}"

# List of security groups in the sib demo project. Format is as required by the
# stackhpc.os-networks role.
# FIXME: Security group rules cannot be assigned to another project, due to
# https://github.com/ansible/ansible/issues/34467, and be created when another
# group with the same name exists in a different project either, due to
# https://github.com/ansible/ansible/issues/30292. These issues will be fixed
# by https://github.com/ansible/ansible/pull/34472 when it is merged. Until
# then, you can use the issue-34467 branch of the stackhpc ansible repo to
# register groups (after uncommenting them):
# https://github.com/stackhpc/ansible/tree/issue-34467.
sib_security_groups: []
  # Default security group for the sib demo project.
  #- name: default
  #  #project: "{{ sib_demo_project.name }}"
  #  rules:
  #    # Allow ICMP (for ping, etc.).
  #    - protocol: icmp
  #    # Allow SSH.
  #    - protocol: tcp
  #      port_range_min: 22
  #      port_range_max: 22

###############################################################################
# Configuration of nova flavors for SIB.

# List of nova flavors in the sib demo project. Format is as required by the
# stackhpc.os-flavors role.
sib_flavors:
  - "{{ sib_flavor_baremetal_A }}"
  - "{{ sib_flavor_m1_tiny }}"
  - "{{ sib_flavor_m1_small }}"
  - "{{ sib_flavor_m1_medium }}"
  - "{{ sib_flavor_m1_large }}"
  - "{{ sib_flavor_m1_xlarge }}"

# Bare metal compute node.
# TBD: Exact configuration of bare metal nodes
sib_flavor_baremetal_A:
  name: "baremetal-A"
  ram: 65536
  disk: 0
  vcpus: 64
  extra_specs:
    "resources:CUSTOM_BAREMETAL_A": 1
    "resources:VCPU": 0
    "resources:MEMORY_MB": 0
    "resources:DISK_GB": 0

# Virtual machine flavors.
sib_flavor_m1_tiny:
  name: "m1.tiny"
  ram: 512
  disk: 1
  vcpus: 1

sib_flavor_m1_small:
  name: "m1.small"
  ram: 2048
  disk: 20
  vcpus: 1

sib_flavor_m1_medium:
  name: "m1.medium"
  ram: 4096
  disk: 40
  vcpus: 2

sib_flavor_m1_large:
  name: "m1.large"
  ram: 8192
  disk: 40
  vcpus: 4

sib_flavor_m1_xlarge:
  name: "m1.xlarge"
  ram: 16384
  disk: 100
  vcpus: 8

###############################################################################
# Software images for SIB

sib_images:
  - "{{ sib_image_centos }}"
  - "{{ sib_image_ubuntu }}"
  - "{{ sib_image_fedora }}"
  - "{{ sib_image_openhpc }}"

# Latest CentOS image
sib_image_centos:
  name: "CentOS7.5"
  elements:
    - "centos7"
    - "epel"
    - "selinux-permissive"
    - "dhcp-all-interfaces"
    - "vm"
  properties:
    os_distro: "centos"
    os_version: "7.5"

# Latest Ubuntu image
sib_image_ubuntu:
  name: "Ubuntu18"
  elements:
    - "ubuntu"
    - "dhcp-all-interfaces"
    - "vm"
  env:
    DIB_RELEASE: "bionic"
  properties:
    os_distro: "ubuntu"
    os_version: "18.04"

# Latest Fedora Core image
sib_image_fedora:
  name: "Fedora27"
  elements:
    - "fedora"
    - "dracut-regenerate"
    - "selinux-permissive"
    - "dhcp-all-interfaces"
    - "vm"
  env:
    DIB_RELEASE: 27
  properties:
    os_distro: "fedora"
    os_version: "27"

# Build of OpenHPC on CentOS
sib_image_openhpc:
  name: "CentOS7.5-OpenHPC"
  elements:
    - "centos7"
    - "epel"
    - "openhpc"
    - "selinux-permissive"
    - "dhcp-all-interfaces"
    - "vm"
  env:
    DIB_OPENHPC_GRPLIST: "ohpc-base-compute ohpc-slurm-client 'InfiniBand Support'"
    DIB_OPENHPC_PKGLIST: >
        ntp fio strace flex bison infiniband-diags boost boost-devel fftw fftw-devel vim emacs git git-lfs
        python34 python34-devel python-virtualenv numpy boost-python
        lmod-ohpc mrsh-ohpc lustre-client-ohpc slurm-ohpc
        gnu7-compilers-ohpc hdf5-gnu7-ohpc openblas-gnu7-ohpc
        mvapich2-gnu7-ohpc scalapack-gnu7-mvapich2-ohpc phdf5-gnu7-mvapich2-ohpc imb-gnu7-mvapich2-ohpc
        openmpi3-gnu7-ohpc scalapack-gnu7-openmpi3-ohpc phdf5-gnu7-openmpi3-ohpc imb-gnu7-openmpi3-ohpc
    DIB_OPENHPC_DELETE_REPO: "n"
  properties:
    os_distro: "centos"
    os_version: "7.5"

# This creates a git checkout in the local user's home directory
sib_image_stackhpc_elements: "{{ ansible_env.PWD }}/stackhpc-image-elements"

sib_image_git_elements:
  - repo: "https://github.com/stackhpc/stackhpc-image-elements.git"
    local: "{{ sib_image_stackhpc_elements }}"

# Path to include
sib_image_elements:
  - "{{ sib_image_stackhpc_elements }}/elements"

