---
- name: Ensure  SIB OpenStack networks exist
  hosts: localhost
  tags:
    - networks
  roles:
    - role: stackhpc.os-networks
      os_networks_venv: "{{ sib_venv }}"
      os_networks_auth_type: "{{ openstack_auth_type }}"
      os_networks_auth: "{{ openstack_auth }}"
      os_networks: "{{ sib_networks }}"
      os_networks_routers: "{{ sib_routers }}"
      os_networks_security_groups: "{{ sib_security_groups }}"
