---
- name: Ensure SIB OpenStack projects exist
  hosts: localhost
  tags:
    - project
  roles:
    - role: stackhpc.os-projects
      os_projects_venv: "{{ sib_venv }}"
      os_projects_auth_type: "{{ openstack_auth_type }}"
      os_projects_admin_auth: "{{ openstack_auth }}"
      os_projects: "{{ sib_projects }}"
